import type { NextRequest } from 'next/server'
import { prisma } from '@souqstudio/db'
import type { Prisma } from '@souqstudio/db'
import { clampOverride, isEmptyOverride } from '@souqstudio/engine'
import type { SlotOverride } from '@souqstudio/types'
import { SLOT_OVERRIDE_LIMITS } from '@souqstudio/types'
import { z } from 'zod'
import { fail, ok } from '@/lib/api'
import { requireApiSession } from '@/lib/api-session'
import { readOverrides } from '@/lib/offer-book-overrides'

/**
 * E6-04 — nudging one card on one page.
 *
 * **A bounded delta, stored against a key that survives next week.** The
 * override names its region and the offer standing in it; re-running the engine
 * with a different product list re-applies the ones whose key still matches and
 * discards the orphans. That is what makes a weekly reissue cheap rather than a
 * rebuild — E6 §1, and the reason unbounded free positioning is refused.
 *
 * **The page row is created on demand.** `createBook` writes no
 * `offer_book_pages` rows: pages are generated by `flowBook` from the master
 * grid, and the row exists only to hold the deltas for a page an owner has
 * actually touched. `@@unique([bookId, index])` is what makes that an upsert.
 */

const schema = z.object({
  regionId: z.string().min(1).max(64),
  /** Null for a static region — a footer band has no offer standing in it. */
  offerId: z.string().min(1).max(64).nullable(),
  offsetX: z.number().optional(),
  offsetY: z.number().optional(),
  imageScale: z.number().optional(),
  /** "Reset to template", per card. Removes the entry rather than zeroing it. */
  reset: z.boolean().optional(),
})

export async function PATCH(
  request: NextRequest,
  { params }: { params: { id: string; index: string } }
) {
  const { session, response } = await requireApiSession({ requireVerifiedEmail: true })
  if (!session) return response

  const pageIndex = Number(params.index)
  if (!Number.isInteger(pageIndex) || pageIndex < 0 || pageIndex > 999) {
    return fail('invalid_page', 'That page is not part of this book.', 422)
  }

  const parsed = schema.safeParse(await request.json().catch(() => null))
  if (!parsed.success) {
    return fail('invalid_request', 'That adjustment could not be applied.', 422)
  }

  // The book and the organization in one predicate, as every route in this epic
  // does — a book that is not theirs returns not-found rather than a row that is
  // then compared.
  const book = await prisma.offerBook.findFirst({
    where: { id: params.id, shop: { organizationId: session.user.organizationId } },
    select: { id: true },
  })
  if (book === null) return fail('not_found', 'That offer book does not exist.', 404)

  const { regionId, offerId, reset, ...delta } = parsed.data

  const page = await prisma.offerBookPage.findUnique({
    where: { bookId_index: { bookId: book.id, index: pageIndex } },
    select: { id: true, slotOverrides: true },
  })

  const existing = readOverrides(page?.slotOverrides)
  const others = existing.filter(
    (entry) => !(entry.regionId === regionId && entry.offerId === offerId)
  )
  const current = existing.find(
    (entry) => entry.regionId === regionId && entry.offerId === offerId
  )

  // **Merged, not replaced.** The panel sends one axis at a time — an owner
  // nudging down and then scaling the image is two requests about one card, and
  // the second must not undo the first.
  const merged: SlotOverride = clampOverride({
    regionId,
    offerId,
    ...current,
    ...(delta.offsetX === undefined ? {} : { offsetX: delta.offsetX }),
    ...(delta.offsetY === undefined ? {} : { offsetY: delta.offsetY }),
    ...(delta.imageScale === undefined ? {} : { imageScale: delta.imageScale }),
  })

  // A delta that changes nothing is not stored. "Reset to template" is the
  // absence of a row, not a row full of zeroes — which is also what makes a
  // reset survive a change to the limits.
  const next =
    reset === true || isEmptyOverride(merged) ? others : [...others, merged]

  await prisma.offerBookPage.upsert({
    where: { bookId_index: { bookId: book.id, index: pageIndex } },
    create: {
      bookId: book.id,
      index: pageIndex,
      slotOverrides: next as unknown as Prisma.InputJsonValue,
    },
    update: { slotOverrides: next as unknown as Prisma.InputJsonValue },
  })

  return ok({
    pageIndex,
    override: next.find((entry) => entry.regionId === regionId && entry.offerId === offerId) ?? null,
    limits: SLOT_OVERRIDE_LIMITS,
  })
}
