import type { NextRequest } from 'next/server'
import { Prisma, prisma } from '@souqstudio/db'
import { z } from 'zod'
import { fail, ok } from '@/lib/api'
import { requireApiSession } from '@/lib/api-session'
import { backgroundSchema, readPageBackground } from '@/lib/offer-book-background'

/**
 * The paper behind one page.
 *
 * **The book's background is still the book's.** `PATCH .../grid` sets what
 * every page draws by default, and most books will never touch this. A page says
 * something different only when an owner deliberately makes it — a cover-ish
 * first page, a clean white page in an otherwise dark book.
 *
 * **Three answers, not two.** Absent is not the same as none: a page that says
 * nothing draws the book's ground, and a page set to none draws plain paper even
 * though the book has one. Without that distinction an owner could put a
 * background on a book and never take it off a single page. `inherit: true`
 * clears the override; `background: null` is the deliberate none.
 *
 * **The page row is created on demand**, exactly as `overrides` and `merges` do:
 * pages are generated by the flow engine from the master grid, and a row exists
 * only to hold what an owner decided about a page they actually touched.
 */

const schema = z.union([
  /* "Go back to whatever the book says." */
  z.object({ inherit: z.literal(true) }),
  /* `null` is the deliberate none — plain paper on this page alone. */
  z.object({ background: backgroundSchema.nullable() }),
])

export async function PATCH(
  request: NextRequest,
  { params }: { params: { id: string; index: string } }
) {
  const { session, response } = await requireApiSession({ requireVerifiedEmail: true })
  if (!session) return response

  const pageIndex = Number(params.index)
  if (!Number.isInteger(pageIndex) || pageIndex < 0 || pageIndex > 999) {
    return fail('invalid_page', 'That page is not part of this book.', 422)
  }

  const parsed = schema.safeParse(await request.json().catch(() => null))
  if (!parsed.success) {
    return fail('invalid_request', 'That background could not be applied.', 422)
  }

  // The book and the organization in one predicate, as every route in this epic
  // does — a book that is not theirs returns not-found rather than a row that is
  // then compared.
  const book = await prisma.offerBook.findFirst({
    where: { id: params.id, shop: { organizationId: session.user.organizationId } },
    select: { id: true },
  })
  if (book === null) return fail('not_found', 'That offer book does not exist.', 404)

  /*
   * **An asset id is an R2 object key, and the key is org-scoped by
   * construction** — `${organizationId}/blocks/${random}`, written by
   * `POST /api/v1/blocks/artwork`. So the tenancy check is a prefix test, and it
   * is the only thing standing between a crafted request and another shop's
   * artwork printed across this page. Same check the grid route makes, for the
   * same reason and against the same absent table.
   */
  if ('background' in parsed.data) {
    const background = parsed.data.background
    if (background !== null && background.from === 'asset') {
      if (!background.assetId.startsWith(`${session.user.organizationId}/`)) {
        return fail('asset_not_found', 'That image is not one of yours.', 404)
      }
    }
  }

  /*
   * **`Prisma.DbNull`, not `null`.** On a `Json?` column Prisma makes you say
   * which null you mean: `JsonNull` stores the JSON value `null` *in* the column,
   * `DbNull` makes the column itself NULL. Only the second is what "this page has
   * no opinion" means, and it is what `readPageBackground` reads as inherit.
   *
   * The deliberate none goes in as `{ background: null }` — an object, not a
   * null — which is the whole reason the value is wrapped: Prisma's two nulls
   * read back identically, so an unwrapped none would be indistinguishable from
   * inherit the moment it came back out.
   */
  const value: Prisma.InputJsonValue | typeof Prisma.DbNull =
    'inherit' in parsed.data
      ? Prisma.DbNull
      : ({ background: parsed.data.background } as unknown as Prisma.InputJsonValue)

  const row = await prisma.offerBookPage.upsert({
    where: { bookId_index: { bookId: book.id, index: pageIndex } },
    create: { bookId: book.id, index: pageIndex, background: value },
    update: { background: value },
    select: { background: true },
  })

  // Read back off what was stored rather than echoed from what was sent, so the
  // editor hears the three states in the same words the next page load will.
  const stored = readPageBackground(row.background)
  return ok({
    pageIndex,
    inherits: stored === undefined,
    background: stored ?? null,
  })
}
