-- E2 Organization Management.
--
-- Two statements in here are NOT generated by Prisma and must not be dropped if
-- this migration is ever regenerated. Both are marked BACKFILL below.
--
-- Note for anyone writing the RLS migration later: the columns in this schema
-- are camelCase and quoted ("organizationId"), because no Prisma field carries
-- an @map. Only the *tables* are snake_case, via @@map. The policy example in
-- souqstudio-technical → references/database.md says organization_id and will
-- not run against this database.

-- ─── organizations: org-level logo and brand kit (E2-01, E2-05) ───────────────
ALTER TABLE "organizations" ADD COLUMN     "brandKit" JSONB,
ADD COLUMN     "logoUrl" TEXT;

-- ─── shops: deactivate, archive, and the seat E3 will write into (E2-02) ──────
ALTER TABLE "shops" ADD COLUMN     "archivedAt" TIMESTAMP(3),
ADD COLUMN     "deactivatedAt" TIMESTAMP(3),
ADD COLUMN     "stripeSubscriptionItemId" TEXT;

-- ─── users: soft removal (E2-03) ──────────────────────────────────────────────
ALTER TABLE "users" ADD COLUMN     "removedAt" TIMESTAMP(3);

-- ─── user_shop_access: tenant column, provenance, timestamps (E2-04) ──────────
-- organizationId is added NULLABLE, backfilled, and only then constrained.
-- Prisma generates a bare `ADD COLUMN ... NOT NULL`, which aborts the whole
-- migration on any database that already holds grant rows. Nothing writes this
-- table today, so it is empty here — but this migration also has to apply
-- cleanly to a database that was pushed to at some later point.
ALTER TABLE "user_shop_access" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "grantedById" TEXT,
ADD COLUMN     "organizationId" TEXT;

-- BACKFILL 1 — every existing grant predates the tenant column.
UPDATE "user_shop_access" usa
SET "organizationId" = s."organizationId"
FROM "shops" s
WHERE s."id" = usa."shopId" AND usa."organizationId" IS NULL;

ALTER TABLE "user_shop_access" ALTER COLUMN "organizationId" SET NOT NULL;
-- updatedAt carries a default only so the backfill can land. Prisma drives the
-- column with @updatedAt from here on; the default is harmless and keeps raw
-- inserts honest.

-- ─── invites (E2-03) ──────────────────────────────────────────────────────────
CREATE TABLE "invites" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "tokenHash" TEXT NOT NULL,
    "invitedById" TEXT NOT NULL,
    "shopGrants" JSONB,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "acceptedAt" TIMESTAMP(3),
    "revokedAt" TIMESTAMP(3),
    "resendCount" INTEGER NOT NULL DEFAULT 0,
    "lastSentAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "invites_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "invites_tokenHash_key" ON "invites"("tokenHash");
CREATE INDEX "invites_organizationId_acceptedAt_idx" ON "invites"("organizationId", "acceptedAt");
CREATE INDEX "invites_expiresAt_idx" ON "invites"("expiresAt");
CREATE UNIQUE INDEX "invites_organizationId_email_key" ON "invites"("organizationId", "email");

-- ─── indexes ──────────────────────────────────────────────────────────────────
CREATE UNIQUE INDEX "shops_stripeSubscriptionItemId_key" ON "shops"("stripeSubscriptionItemId");
CREATE INDEX "shops_organizationId_idx" ON "shops"("organizationId");
CREATE INDEX "shops_organizationId_archivedAt_idx" ON "shops"("organizationId", "archivedAt");
CREATE INDEX "user_shop_access_shopId_idx" ON "user_shop_access"("shopId");
CREATE INDEX "user_shop_access_organizationId_idx" ON "user_shop_access"("organizationId");
CREATE INDEX "users_organizationId_removedAt_idx" ON "users"("organizationId", "removedAt");

-- ─── foreign keys ─────────────────────────────────────────────────────────────
ALTER TABLE "user_shop_access" ADD CONSTRAINT "user_shop_access_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "user_shop_access" ADD CONSTRAINT "user_shop_access_grantedById_fkey" FOREIGN KEY ("grantedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "invites" ADD CONSTRAINT "invites_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "invites" ADD CONSTRAINT "invites_invitedById_fkey" FOREIGN KEY ("invitedById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- BACKFILL 2 — lift each organization's brand kit up from its oldest shop.
--
-- This is the statement that decides whether every account created before E2
-- keeps its brand. Every shop already carries brandOverride = 'inherit' (the
-- schema default, and nothing has ever written another value), so the moment
-- resolveBrandKit() goes live an inheriting shop reads the *organization's*
-- kit. Without this, that kit is NULL and every existing shop loses its
-- colours, grid and template on deploy.
--
-- Signup creates exactly one shop per organization, so "the oldest shop" is
-- "the only shop" for every row that exists today and the lift is lossless.
UPDATE "organizations" o
SET "brandKit" = s."brandKit", "logoUrl" = s."logoUrl"
FROM (
  SELECT DISTINCT ON ("organizationId") "organizationId", "brandKit", "logoUrl"
  FROM "shops"
  ORDER BY "organizationId", "createdAt" ASC
) s
WHERE s."organizationId" = o."id" AND o."brandKit" IS NULL;
