import type { NextRequest } from 'next/server'
import { prisma } from '@souqstudio/db'
import type { Prisma } from '@souqstudio/db'
import { normalizeMerges } from '@souqstudio/engine'
import { z } from 'zod'
import { fail, ok } from '@/lib/api'
import { requireApiSession } from '@/lib/api-session'
import { toMasterGrid } from '@/lib/offer-book-compose'
import { readGridChoice } from '@/lib/offer-book-grid'

/**
 * The cells one page draws as one. Composition model §4, per page.
 *
 * **A merge belongs to the page it was made on.** It was briefly a property of
 * the master grid, which meant merging two cells on page one merged them on all
 * nine — the model's stated behaviour, and not what an owner laying out a
 * booklet wants: a hero belongs to the page they put it on. So the master
 * carries the tracks, the bands and the paper, and this carries what a single
 * page does with them.
 *
 * **The flow stays continuous across the seam.** A page holding a merged hero
 * holds one card fewer and the products carry on onto the next page; nothing
 * restarts and nothing is dropped. `flowBook` runs one cursor over the whole
 * book and asks each page only for its own cells.
 *
 * **The whole set, never one merge.** Two tabs merging against different
 * starting states would interleave into a layout neither owner chose — the same
 * reasoning the offer tray's reorder uses when it sends the whole order rather
 * than a `{from, to}`. The client computes the new set and posts it.
 *
 * **The page row is created on demand**, exactly as `overrides` does: pages are
 * generated by the flow engine from the master, and a row exists only to hold
 * what an owner decided about a page they actually touched.
 */

const mergeSchema = z.object({
  colStart: z.number().int().min(0).max(5),
  colEnd: z.number().int().min(0).max(5),
  rowStart: z.number().int().min(0).max(7),
  rowEnd: z.number().int().min(0).max(7),
})

const schema = z.object({
  /** Forty-eight is the largest grid the layout route allows, so nothing can
   *  name more merges than cells. */
  merges: z.array(mergeSchema).max(48),
})

export async function PATCH(
  request: NextRequest,
  { params }: { params: { id: string; index: string } }
) {
  const { session, response } = await requireApiSession({ requireVerifiedEmail: true })
  if (!session) return response

  const pageIndex = Number(params.index)
  if (!Number.isInteger(pageIndex) || pageIndex < 0 || pageIndex > 999) {
    return fail('invalid_page', 'That page is not part of this book.', 422)
  }

  const parsed = schema.safeParse(await request.json().catch(() => null))
  if (!parsed.success) {
    return fail('invalid_request', 'That layout could not be applied.', 422)
  }

  // The book and the organization in one predicate, as every route in this epic
  // does — a book that is not theirs returns not-found rather than a row that is
  // then compared.
  const book = await prisma.offerBook.findFirst({
    where: { id: params.id, shop: { organizationId: session.user.organizationId } },
    select: {
      id: true,
      format: true,
      grids: {
        where: { role: 'master' },
        select: { cols: true, rows: true, gap: true, margin: true, background: true, regions: true },
        take: 1,
      },
    },
  })
  if (book === null) return fail('not_found', 'That offer book does not exist.', 404)

  const master = book.grids[0]
  if (master === undefined) {
    return fail('no_master_grid', 'This book has no layout to change.', 409)
  }

  /*
   * **Bounded against the master the page is actually an instance of**, not
   * against the schema's own ceiling. A merge reaching column three is fine on a
   * four-wide book and describes nothing on a two-wide one, and the honest
   * response to the second is to drop it rather than to store a span no page can
   * draw. `normalizeMerges` also refuses inverted spans, single cells and two
   * merges claiming one cell.
   */
  const choice = readGridChoice(book.format, toMasterGrid(master))
  const merges = normalizeMerges(parsed.data.merges, {
    perRow: choice.perRow ?? master.cols.length,
    bodyRows: choice.bodyRows ?? 1,
  })

  await prisma.offerBookPage.upsert({
    where: { bookId_index: { bookId: book.id, index: pageIndex } },
    create: {
      bookId: book.id,
      index: pageIndex,
      merges: merges as unknown as Prisma.InputJsonValue,
    },
    update: { merges: merges as unknown as Prisma.InputJsonValue },
  })

  // What was stored, not what was sent. A merge the grid could not hold was
  // dropped above, and the editor has to hear that rather than go on drawing a
  // selection around a hero the page does not have.
  return ok({ pageIndex, merges })
}
